rpc:
  server:
    enable: true
    host: 127.0.0.1
    serviceName: oss-service
  curatorProperties:
    retryCount: 5
    elapsedTimeMs: 5000
    connectString: 127.0.0.1:2181
    sessionTimeoutMs: 60000
    connectionTimeoutMs: 5000

spring:
  application:
    name: oss-service
  profiles:
    active: server1